In [1]:
#Name: Nikita Parmar
#Enrollment No:216270307099

'''5.1->o find the maximum and minimum value of a given flattened array'''

import numpy as np
Arr = np.array([[101, 201, 301],[401, 501, 601],[701, 801, 
901]])
# Flattening the array 
flattened = Arr.flatten()
# Maximum and Minimum values from the flattened array
max_value = np.max(flattened)
min_value = np.min(flattened)
print(Arr)
print("\nMaximum value :", max_value)
print("Minimum value :", min_value)


[[101 201 301]
 [401 501 601]
 [701 801 901]]

Maximum value : 901
Minimum value : 101


In [2]:
'''5.2->to compute the mean, standard deviation, and variance of a given 
array along the second axis'''

mean_sa = np.mean(Arr, axis=1)
std_deviation = np.std(Arr, axis=1)
variance = np.var(Arr, axis=1)
print(Arr)
print("\nMean along the second axis:", mean_sa)
print("\nStandard Deviation along the second axis:", 
std_deviation)
print("\nVariance along the second axis:", variance)


[[101 201 301]
 [401 501 601]
 [701 801 901]]

Mean along the second axis: [201. 501. 801.]

Standard Deviation along the second axis: [81.64965809 81.64965809 81.64965809]

Variance along the second axis: [6666.66666667 6666.66666667 6666.66666667]
