In [1]:
#Name: Nikita Parmar
#Enrollment No:216270307099

'''4.1->to add, subtract, multiply, divide arguments element-wise '''
import numpy as np
# Adding, Subtracting, Multiplying and Dividing Arrays element-wise
# Defining arrays:
Arr1 = np.array([11,13,15])
Arr2 = np.array([2,4,6])
print(Arr1 , " + " , Arr2 ,"= " ,np.add(Arr1,Arr2))
print(Arr1 , " - ", Arr2, "= " , np.subtract(Arr1,Arr2))
print(Arr1 , " x ", Arr2, "= " ,np.multiply(Arr1,Arr2))
print(Arr1 , " % ", Arr2, "= " ,np.divide(Arr1,Arr2))


[11 13 15]  +  [2 4 6] =  [13 17 21]
[11 13 15]  -  [2 4 6] =  [9 9 9]
[11 13 15]  x  [2 4 6] =  [22 52 90]
[11 13 15]  %  [2 4 6] =  [5.5  3.25 2.5 ]


In [2]:
'''4.2->to round elements of the array to the nearest integer'''

# Rounding elements to nearest integers
Arr3 = np.array([1.6,5.5,10.4])
print("Rounding off elements of Array", Arr3 , ": " ,np.round(Arr3))

Rounding off elements of Array [ 1.6  5.5 10.4] :  [ 2.  6. 10.]


In [3]:
'''4.3->to calculate mean across dimension, in a 2D numpy array'''

# Calculating mean columnwise and rowwise
Arr4 = np.array([[100,200,300],[400,500,600]])
print(Arr4)
print("\nColumnwise Mean: ", np.mean(Arr4,axis=0))
print("Rowwise Mean: " , np.mean(Arr4,axis=1))

[[100 200 300]
 [400 500 600]]

Columnwise Mean:  [250. 350. 450.]
Rowwise Mean:  [200. 500.]


In [4]:
'''4.4->to calculate the difference between neighboring elements, elementwise of a given array'''

# Calculating difference between neighbouring elements

Array: [[100,200,300],[400,500,600]]
print(Arr4 , "\n\nDifference columnwise:-\n",np.diff(Arr4,axis=0))
print("\nDifference rowwise:-\n",np.diff(Arr4,axis=1))

[[100 200 300]
 [400 500 600]] 

Difference columnwise:-
 [[300 300 300]]

Difference rowwise:-
 [[100 100]
 [100 100]]
